/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class masud_shifuddin_directionpointer_NativeLibrary */

#ifndef _Included_masud_shifuddin_directionpointer_NativeLibrary
#define _Included_masud_shifuddin_directionpointer_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     masud_shifuddin_directionpointer_NativeLibrary
 * Method:    fetch_ident
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_masud_shifuddin_directionpointer_NativeLibrary_fetch_1ident
  (JNIEnv *, jobject, jstring file_name);

/*
 * Class:     masud_shifuddin_directionpointer_NativeLibrary
 * Method:    match_ident
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_masud_shifuddin_directionpointer_NativeLibrary_match_1ident
  (JNIEnv *, jobject, jstring file_name);

/*
 * Class:     masud_shifuddin_directionpointer_NativeLibrary
 * Method:    false_ident
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_masud_shifuddin_directionpointer_NativeLibrary_false_1ident
  (JNIEnv *, jobject, jstring file_name);

#ifdef __cplusplus
}
#endif
#endif
